# ServerProperties 配置类
# 项目启动端口
server:
  # 项目启动端口
  port: 8888
  # 项目启动名（路径）
  servlet:
    context-path: /community

# ThymeleafProperties
# 开发时关闭thymeleaf模板引擎缓存
spring:
  thymeleaf:
    cache: false

  # DataSourceAutoConfiguration
  # 数据源配置
  datasource:
    # 数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最大连接数
      maximum-pool-size: 15
      # 最小连接数
      minimum-idle: 5
      # 空闲时间（ms）
      idle-timeout: 30000

  # MailSenderAutoConfiguration  邮箱参数配置
  mail:
    # 邮箱域名
    host: smtp.qq.com
    # 端口（几乎所有邮箱默认的端口都是 465）
    port: 465
    # 邮箱的账号（自己定义也可以）密码(QQ邮箱的密码要改为QQ邮箱的授权码)
    username: cbq981@qq.com
    password: oxhmwzttexdybaji
    # 协议 (后面加个s表示它使用的是加密的smtp协议)
    protocol: smtps
    # 其他配置 Map数据类型  采用ssl安全连接的方式
    properties: {mail.smtp.ssl.enable : true}

  # RedisAutoConfiguration   Redis自动配置类
  redis:
    # 哪个库  0-15
    database: 11
    # ip
    host: localhost
    # 端口
    port: 6379
    # 其他参数都用默认值

  # KafkaProperties
  # kafka配置
  kafka:
    # 服务器（9092） server
    bootstrap-servers: localhost:9092
    # 消费者 consumer
    consumer:
      # 消费者分组id
      group-id: test-consumer-group
      # 是否自动提交消费者的偏移量offset
      enable-auto-commit: true
      # 自动提交的频率（ms）
      auto-commit-interval: 3000

  # ElasticsearchProperties
  # Elasticsearch 配置（7.x版本需要编写配置类）

  # Spring 线程池配置
  task:
    # TaskExecutionProperties
    execution:
      pool:
        # 最大线程数量
        max-size: 15
        # 核心线程数量（线程池创建好后默认自带5个线程，不够用时自动扩容直至15个）
        core-size: 5
        # 队列的容量（任务等待队列）
        queue-capacity: 100
    # TaskSchedulingProperties
    scheduling:
      pool:
        size: 5

  # Spring Quartz 配置
  # QuartzProperties
  quartz:
    # 任务的存储方式
    job-store-type: jdbc
    # 调度器的名字
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          # 调度器的id自动生成
          scheduler:
            instanceId: AUTO
          jobStore:
            # 执行任务存到数据库中的类
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            # JDBC的驱动
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 是否采用集群的方式
            isClustered: true
          # 使用哪个线程池
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

# MybatisProperties
# mybatis 配置
mybatis:
  # mapper 映射文件路径
  mapper-locations: classpath:mapper/*.xml
  # mapper对应实体类所在包(可以在mapper.xml中省略实体类的全限定包名)
  type-aliases-package: com.study.community.entity
  configuration:
    # 启用自动生成主键（自增长字段）
    use-generated-keys: true
    # 自动适应驼峰式命名
    map-underscore-to-camel-case: true

# 日志配置 更复杂的logback配置在logback-spring（只要是这个名字，spring就会自动识别并启动它）中
#logging:
#  level:
#    com.study.community.dao: debug
#  file:
#    path: D:/study/idea-workspace/SpringBoot-bbs/community/community.log

# 自定义的配置 community
community:
  path:
    # 域名（没有正式的域名，就先写本机的地址）
    domain: http://localhost:8888
    # 上传文件保存的路径
    upload: d:/study/idea-workspace/SpringBoot-bbs/upload-imgs

# 自定义的配置 wk
wk:
  image:
    # 命令前缀（相同部分）
    command: D:/study/wkhtmltopdf/wkhtmltox-0.12.6-1.msvc2015-win64/bin/wkhtmltoimage
    # 生成图片存放路径（文件夹）
    storage: d:/study/wkhtmltopdf/wk-images

# 自定义的配置 caffeine 单独使用（不整合到spring） 缓存工具
caffeine:
  # 帖子的缓存
  discuss:
    # 最大缓存数量
    max-size: 15
    # 缓存过期时间 单位是秒  定时自动淘汰
    expire-seconds: 180



